name: Build linux shared library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make script executable
      run: chmod +x ./scripts/build.sh
    - name: build
      run: ./scripts/build.sh
