name: Build mac shared library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: get pre-requirments
      run: brew install qt ninja
    - name: make script executable
      run: chmod +x ./scripts/build-mac-ci.sh
    - name: build
      run: ./scripts/build-mac-ci.sh
