name: Build mac shared library

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: get pre-requirments
      run: brew install qt ninja
    - name: add qt to path
      run: echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile
    - name: make script executable
      run: chmod +x ./scripts/build.sh
    - name: build
      run: ./scripts/build.sh
